### PR TITLE
Setup php-build in separate docker layer

### PR DESCRIPTION
**Pull request by glensc**
This adds separate layers for some steps allowing to cache and build in parallel.

This is a prelude of an idea to build other 5.x from source:
- https://github.com/shivammathur/php5-ubuntu/pull/1#issuecomment-753980535

fpm and embed are built parallel:

image

### CODE REVIEW

**Comment by shivammathur** [comment]
@glensc is this PR ready to merge?

**Comment by glensc** [comment]
Looks like the build fails. Changed back to Draft

**Comment by glensc** [comment]
Fixed with f538f6f. Ready for review/merge.

**Comment by glensc** [comment]
@shivammathur please don't squash merge my PR's, it makes it very difficult to rebase and resolve conflicts, that's why I haven't been able to push out the changes I promised:
- https://github.com/shivammathur/php5-ubuntu/pull/1#issuecomment-773856902

**Pull request merged**
